
import './App.css';
import Data from './Data';
import Card from './Card';

function App() {
  return (
   <>
   
   
   <Card
   imgsrc={Data[0].imgsrc}
   title={Data[0].title}
   sname={Data[0].sname}
   city={Data[0].city}
   course={Data[0].course}
   date={Data[0].date}
   time={Data[0].time}
   age={Data[0].age}
   number={Data[0].number}
   link={Data[0].link}
   />
   <Card
   imgsrc={Data[1].imgsrc}
   title={Data[1].title}
   sname={Data[1].sname}
   city={Data[1].city}
   course={Data[1].course}
   date={Data[1].date}
   time={Data[1].time}
   age={Data[1].age}
   number={Data[1].number}
   link={Data[1].link}
   />
   <Card
   imgsrc={Data[2].imgsrc}
   title={Data[2].title}
   sname={Data[2].sname}
   city={Data[2].city}
   course={Data[2].course}
   date={Data[2].date}
   time={Data[2].time}
   age={Data[2].age}
   number={Data[2].number}
   link={Data[2].link}
   />
   <Card
   imgsrc={Data[3].imgsrc}
   title={Data[3].title}
   sname={Data[3].sname}
   city={Data[3].city}
   course={Data[3].course}
   date={Data[3].date}
   time={Data[3].time}
   age={Data[3].age}
   number={Data[3].number}
   link={Data[3].link}
   />
   <Card
   imgsrc={Data[4].imgsrc}
   title={Data[4].title}
   sname={Data[4].sname}
   city={Data[4].city}
   course={Data[4].course}
   date={Data[4].date}
   time={Data[4].time}
   age={Data[4].age}
   number={Data[4].number}
   link={Data[4].link}
   />
   <Card
   imgsrc={Data[5].imgsrc}
   title={Data[5].title}
   sname={Data[5].sname}
   city={Data[5].city}
   course={Data[5].course}
   date={Data[5].date}
   time={Data[5].time}
   age={Data[5].age}
   number={Data[5].number}
   link={Data[5].link}
   />
   <Card
   imgsrc={Data[6].imgsrc}
   title={Data[6].title}
   sname={Data[6].sname}
   city={Data[6].city}
   course={Data[6].course}
   date={Data[6].date}
   time={Data[6].time}
   age={Data[6].age}
   number={Data[6].number}
   link={Data[6].link}
   />
   <Card
   imgsrc={Data[7].imgsrc}
   title={Data[7].title}
   sname={Data[7].sname}
   city={Data[7].city}
   course={Data[7].course}
   date={Data[7].date}
   time={Data[7].time}
   age={Data[7].age}
   number={Data[7].number}
   link={Data[7].link}
   />
   <Card
   imgsrc={Data[8].imgsrc}
   title={Data[8].title}
   sname={Data[8].sname}
   city={Data[8].city}
   course={Data[8].course}
   date={Data[8].date}
   time={Data[8].time}
   age={Data[8].age}
   number={Data[8].number}
   link={Data[8].link}
   />
   <Card
   imgsrc={Data[9].imgsrc}
   title={Data[9].title}
   sname={Data[9].sname}
   city={Data[9].city}
   course={Data[9].course}
   date={Data[9].date}
   time={Data[9].time}
   age={Data[9].age}
   number={Data[9].number}
   link={Data[9].link}
   />
   </>
  );
}

export default App;
